language: ruby
rvm: 2.4.1

cache:
  bundler: true
  directories:
    - node_modules
    - $TRAVIS_BUILD_DIR/build
    - $TRAVIS_BUILD_DIR/data/contenido


script:
  - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
        bundle exec middleman build --no-parallel;
        bundle exec middleman s3_sync;
    fi'
